### ISSUE TITLE
Make Tracker optional where PeerJS peer discovery is avaliable

### ISSUE THREAD

**Issue by qgustavor** [sheab/senet#1]
PeerJS servers can be configured to allow each peer to find each other using the [`allow_discovery`](https://github.com/peers/peerjs-server/blob/0c8f4b8525df9b3681ece41014e3fd5ffad9dc1e/bin/peerjs#L60) setting and the [.listAllPeers() method](https://github.com/peers/peerjs/blob/1a4cea3c6c78a2b91fd89af4bccd6650f021d57b/lib/peer.js#L451-495). Seems Tracker server is needed just for servers without this feature, as it is off by default and also undocumented.

By adapting the framework to use the PeerJS peer discovery instead of Tracker it can reduce the number of required components, requiring less from the server.

**Comment by sheab** [comment]
I had this idea too, but there are several reasons I went with making my own tracker rather than using PeerJS's `allow_discovery`.

First off, the PeerJS server is "dumb". One peer server can host any number of games, or versions of games. Different games, or different versions of the same game are completely incompatible. The tracker solves this by using the `senet.compatibilityHash` string to only match compatible clients. Because the PeerJS server doesn't support this, clients might have to keep trying a while to find another compatible client.

Second off, the `listAllPeers()` method is a very inefficient way of doing things. Let's say there are 1000 peers connected to a PeerJS server, playing 20 different games. Should a client looking for peers receive an array of 1000 peerIDs and just try connecting to each one hoping that it is 1. compatible, 2. not in a full game, 3. actually wants to be joined. That's the third thing - `allow_discovery` prevents people from having private games.

The one way I can see this working is if you had a PeerJS server specifically assigned to host one version of one game (where it was ok if players couldn't have a private game). Then you forked PeerJS to include a new method `listSomePeers`, so it doesn't return a ginormous array.

It is a noble idea though - removing as many server components as possible. If we did implement this, I think it would be better done using a method similar to the way DHT peer discovery works.
